// w3c.github.io/html-reference/elements-by-function.html
// github.com/sindresorhus/html-tags

type HTMLTagMapping = {
    html: String,
    sketchComponent: String,
};

// sorted by sketch renderers
const htmlTagsMap = {
    BLACKLIST: [
        'header',
        'noscript',
        'html',
        'script',
        'source',
        'style',
        'param',
        'template',
        'track',
        'var',
        'video',
        'wbr',
        'area',
        'base',
        'embed',
        'meta',
        'page',
    ],
    artboard: ['document', 'doc', 'body', 'head', 'header', 'html'],
    image: ['figure', 'img', 'picture', 'img'],
    text: [
        'a',
        'abbr',
        'address',
        'article',
        'br',
        'cite',
        'caption',
        'data',
        'datalist',
        'dd',
        'del',
        'dfn',
        'details',
        'em',
        'figcaption',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'i',
        'li',
        'link',
        'ol',
        'p',
        'pre',
        'small',
        'span',
        'strong',
        'sub',
        'sup',
        'title',
        'u',
        'ul',
        'br',
    ],
    view: [
        'area',
        'aside',
        'audio',
        'base',
        'bdi',
        'bdo',
        'blockquote',
        'button',
        'canvas',
        'code',
        'dialog',
        'div',
        'dl',
        'dt',
        'embed',
        'fieldset',
        'footer',
        'form',
        'hgroup',
        'hr',
        'input',
        'ins',
        'kbd',
        'keygen',
        'label',
        'legend',
        'main',
        'map',
        'mark',
        'math',
        'menu',
        'menuitem',
        'meta',
        'meter',
        'nav',
        'object',
        'optgroup',
        'option',
        'output',
        'progress',
        'q',
        'rb',
        'rp',
        'rt',
        'rtc',
        'ruby',
        's',
        'samp',
        'section',
        'select',
        'slot',
        'table',
        'tbody',
        'td',
        'tfoot',
        'th',
        'thead',
        'tr',
        'textarea',
        'col',
        'hr',
    ],
    svg: ['svg'],
};

export const HTML2SketchComponentsMap: Array<HTMLTagMapping> = [];
Object.keys(htmlTagsMap).forEach((sketchComponent: String) => {
    HTML2SketchComponentsMap.push(
        ...htmlTagsMap[sketchComponent].map(tag => ({ html: tag, sketchComponent })),
    );
});

export default htmlTagsMap;
